export 'package:portfolio/screens/alert_screen.dart';
export 'package:portfolio/screens/card_screen.dart';
export 'package:portfolio/screens/listview1_screen.dart';
export 'package:portfolio/screens/listview2_screen.dart';
export 'package:portfolio/screens/home_screen.dart';
export 'package:portfolio/screens/avatar_screen.dart';
export 'package:portfolio/screens/animated_screen.dart';
export 'package:portfolio/screens/inputs_screen.dart';
export 'package:portfolio/screens/slider_screen.dart';
